package io.github.miklires.mevents.event;

import io.github.miklires.mevents.api.*;import io.github.miklires.mevents.storage.EventRepository;import io.github.miklires.mevents.util.PluginScheduler;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.block.Barrel;import org.bukkit.command.ConsoleCommandSender;import org.bukkit.entity.*;import org.bukkit.plugin.Plugin;
import java.time.Instant;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.AtomicBoolean;import java.util.random.RandomGenerator;

public final class EventService implements MEventsApi {
    private final Plugin plugin;private final EventCatalog catalog;private final EventRepository repository;private final PluginScheduler scheduler;private final RewardSelector rewards=new RewardSelector(RandomGenerator.getDefault());
    private final ConcurrentMap<UUID,RuntimeEvent> running=new ConcurrentHashMap<>();private final ConcurrentMap<UUID,UUID> bosses=new ConcurrentHashMap<>();private final ConcurrentMap<BlockKey,UUID> drops=new ConcurrentHashMap<>();
    public EventService(Plugin plugin,EventCatalog catalog,EventRepository repository){this.plugin=plugin;this.catalog=catalog;this.repository=repository;this.scheduler=new PluginScheduler(plugin);}
    public CompletableFuture<EventRunView> start(String templateId){EventDefinition d=catalog.find(templateId).orElseThrow(()->new IllegalArgumentException("Unknown event: "+templateId));return active(templateId).thenCompose(existing->{if(existing.isPresent())return CompletableFuture.failedFuture(new IllegalStateException("Event is already running"));UUID id=UUID.randomUUID();return repository.create(id,d.id(),d.type(),d.world(),d.x(),d.y(),d.z()).thenCompose(view->repository.transition(id,EventState.SCHEDULED,EventState.PREPARING,null,null,"countdown").thenApply(ok->{if(!ok)throw new IllegalStateException("Could not prepare event");running.put(id,new RuntimeEvent(id,d));scheduler.later(d.preparationTicks(),()->activate(id));scheduler.later(d.preparationTicks()+d.durationTicks(),()->cancel(id,"timeout"));broadcast("§6[mEvents] §f"+d.displayName()+" начнётся через "+Math.max(1,d.preparationTicks()/20)+" сек.");return view;}));});}
    private void activate(UUID id){RuntimeEvent runtime=running.get(id);if(runtime==null)return;Instant now=Instant.now(),end=now.plusMillis(runtime.definition.durationTicks()*50);repository.transition(id,EventState.PREPARING,EventState.ACTIVE,now,end,"active").thenAccept(ok->{if(!ok)return;scheduler.global(()->{World world=Bukkit.getWorld(runtime.definition.world());if(world==null){cancel(id,"world unavailable");return;}Location location=new Location(world,runtime.definition.x(),runtime.definition.y(),runtime.definition.z());if(runtime.definition.type()==EventType.AIRDROP)spawnDrop(runtime,location);else spawnBoss(runtime,location);broadcast("§6[mEvents] §f"+runtime.definition.displayName()+" началось: §e"+location.getBlockX()+" "+location.getBlockY()+" "+location.getBlockZ());});});}
    private void spawnDrop(RuntimeEvent runtime,Location location){scheduler.region(location,()->{location.getBlock().setType(Material.BARREL,false);if(location.getBlock().getState() instanceof Barrel barrel){barrel.customName(net.kyori.adventure.text.Component.text(runtime.definition.displayName()));barrel.update(true);}runtime.location=location;drops.put(BlockKey.of(location),runtime.id);});}
    private void spawnBoss(RuntimeEvent runtime,Location location){scheduler.region(location,()->{EntityType type=EntityType.valueOf(runtime.definition.bossEntity().toUpperCase(Locale.ROOT));Entity raw=location.getWorld().spawnEntity(location,type);if(!(raw instanceof LivingEntity boss)){raw.remove();cancel(runtime.id,"configured entity is not living");return;}boss.customName(net.kyori.adventure.text.Component.text(runtime.definition.displayName()));boss.setCustomNameVisible(true);var max=boss.getAttribute(Attribute.MAX_HEALTH);if(max!=null)max.setBaseValue(runtime.definition.bossHealth());boss.setHealth(Math.min(runtime.definition.bossHealth(),max==null?boss.getHealth():max.getValue()));boss.setPersistent(false);runtime.boss=boss;runtime.location=location;bosses.put(boss.getUniqueId(),runtime.id);});}
    public boolean claimDrop(Player player,Location location){UUID id=drops.get(BlockKey.of(location));if(id==null)return false;RuntimeEvent runtime=running.get(id);if(runtime==null||!runtime.claimed.compareAndSet(false,true))return true;RewardDefinition reward=rewards.select(runtime.definition);repository.journalReward(id,player.getUniqueId(),player.getName(),reward.id()).thenAccept(tx->scheduler.global(()->deliver(tx,reward)));complete(id,"claimed by "+player.getName());return true;}
    public void recordDamage(UUID entity,Player player,double damage){UUID run=bosses.get(entity);if(run!=null)repository.addDamage(run,player.getUniqueId(),player.getName(),damage);}
    public void bossDied(UUID entity){UUID id=bosses.remove(entity);if(id==null)return;RuntimeEvent runtime=running.get(id);if(runtime==null)return;repository.contributions(id).thenAccept(list->{for(var contribution:list){RewardDefinition reward=rewards.select(runtime.definition);repository.journalReward(id,contribution.playerId(),contribution.playerName(),reward.id()).thenAccept(tx->scheduler.global(()->deliver(tx,reward)));}complete(id,"boss defeated");});}
    private void deliver(EventRepository.RewardTransaction tx,RewardDefinition reward){ConsoleCommandSender console=Bukkit.getConsoleSender();for(String command:reward.commands())Bukkit.dispatchCommand(console,command.replace("{player}",tx.playerName()).replace("{run}",tx.runId().toString()));repository.markDelivered(tx.transactionId());Player player=Bukkit.getPlayer(tx.playerId());if(player!=null)player.sendMessage("§aНаграда события получена: §f"+reward.id());}
    public void retryPending(){repository.pendingRewards().thenAccept(list->scheduler.global(()->list.forEach(tx->catalog.reward(tx.rewardId()).ifPresent(reward->deliver(tx,reward)))));}
    private void complete(UUID id,String detail){RuntimeEvent runtime=running.remove(id);if(runtime==null)return;cleanup(runtime);repository.transition(id,EventState.ACTIVE,EventState.COMPLETED,null,null,detail);broadcast("§6[mEvents] §f"+runtime.definition.displayName()+" завершено.");}
    @Override public CompletableFuture<Boolean> cancel(UUID id,String reason){RuntimeEvent runtime=running.remove(id);if(runtime==null)return CompletableFuture.completedFuture(false);cleanup(runtime);return repository.active(runtime.definition.id()).thenCompose(view->{if(view.isEmpty())return CompletableFuture.completedFuture(false);return repository.transition(id,view.get().state(),EventState.CANCELLED,null,null,reason);});}
    private void cleanup(RuntimeEvent runtime){if(runtime.boss!=null){bosses.remove(runtime.boss.getUniqueId());scheduler.entity(runtime.boss,runtime.boss::remove);}if(runtime.location!=null&&runtime.definition.type()==EventType.AIRDROP){drops.remove(BlockKey.of(runtime.location));scheduler.region(runtime.location,()->{if(runtime.location.getBlock().getType()==Material.BARREL)runtime.location.getBlock().setType(Material.AIR,false);});}}
    public boolean protects(Location location){return drops.containsKey(BlockKey.of(location));}
    public Collection<RuntimeView> runtimeViews(){return running.values().stream().map(r->new RuntimeView(r.id,r.definition.id(),r.definition.displayName(),r.definition.type())).toList();}
    public void shutdown(){for(UUID id:List.copyOf(running.keySet()))cancel(id,"plugin disabled").join();}
    private void broadcast(String text){scheduler.global(()->Bukkit.broadcast(net.kyori.adventure.text.Component.text(text.replace('§','&'))));}
    @Override public Collection<String> templateIds(){return catalog.all().stream().map(EventDefinition::id).toList();}
    @Override public CompletableFuture<Optional<EventRunView>> active(String templateId){return repository.active(templateId);}
    private static Player attacker(org.bukkit.event.entity.EntityDamageByEntityEvent e){if(e.getDamager() instanceof Player p)return p;if(e.getDamager() instanceof org.bukkit.entity.Projectile projectile&&projectile.getShooter() instanceof Player p)return p;return null;}
    public static Player playerAttacker(org.bukkit.event.entity.EntityDamageByEntityEvent e){return attacker(e);}
    private static final class RuntimeEvent{final UUID id;final EventDefinition definition;final AtomicBoolean claimed=new AtomicBoolean();volatile Location location;volatile LivingEntity boss;RuntimeEvent(UUID id,EventDefinition definition){this.id=id;this.definition=definition;}}
    private record BlockKey(UUID world,int x,int y,int z){static BlockKey of(Location l){return new BlockKey(Objects.requireNonNull(l.getWorld()).getUID(),l.getBlockX(),l.getBlockY(),l.getBlockZ());}}
    public record RuntimeView(UUID id,String template,String name,EventType type){}
}
