package io.github.miklires.mevents.storage;

import io.github.miklires.mevents.api.*;
import java.nio.file.Path;
import java.sql.*;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.*;

public final class EventRepository implements AutoCloseable {
    private final String url;
    private final ExecutorService executor = Executors.newSingleThreadExecutor(Thread.ofVirtual().name("mevents-db-", 0).factory());

    public EventRepository(Path file) { this("jdbc:h2:" + file.toAbsolutePath() + ";AUTO_SERVER=TRUE"); }
    EventRepository(String url) { this.url = url; }

    public CompletableFuture<Void> initialize() { return run(() -> {
        try (Connection c = connection(); Statement s = c.createStatement()) {
            s.executeUpdate("CREATE TABLE IF NOT EXISTS event_runs(run_id UUID PRIMARY KEY, template_id VARCHAR(80) NOT NULL, event_type VARCHAR(20) NOT NULL, state VARCHAR(20) NOT NULL, world VARCHAR(128) NOT NULL, x INT NOT NULL, y INT NOT NULL, z INT NOT NULL, created_at TIMESTAMP WITH TIME ZONE NOT NULL, started_at TIMESTAMP WITH TIME ZONE, ends_at TIMESTAMP WITH TIME ZONE, detail VARCHAR(512))");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS event_contributions(run_id UUID NOT NULL, player_id UUID NOT NULL, player_name VARCHAR(32) NOT NULL, damage DOUBLE PRECISION NOT NULL, PRIMARY KEY(run_id,player_id))");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS event_rewards(transaction_id UUID PRIMARY KEY, run_id UUID NOT NULL, player_id UUID NOT NULL, player_name VARCHAR(32) NOT NULL, reward_id VARCHAR(80) NOT NULL, delivered BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
            s.executeUpdate("CREATE TABLE IF NOT EXISTS event_audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, run_id UUID, action VARCHAR(64) NOT NULL, detail VARCHAR(512), created_at TIMESTAMP WITH TIME ZONE NOT NULL)");
        }
    }); }

    public CompletableFuture<EventRunView> create(UUID id, String template, EventType type, String world, int x, int y, int z) { return supply(() -> {
        Instant now = Instant.now();
        try (Connection c = connection(); PreparedStatement p = c.prepareStatement("INSERT INTO event_runs VALUES(?,?,?,?,?,?,?,?,?,?,?,?)")) {
            p.setObject(1,id); p.setString(2,template); p.setString(3,type.name()); p.setString(4,EventState.SCHEDULED.name()); p.setString(5,world); p.setInt(6,x); p.setInt(7,y); p.setInt(8,z); p.setObject(9,now); p.setObject(10,null); p.setObject(11,null); p.setString(12,null); p.executeUpdate();
        }
        audit(id,"CREATED",template);
        return new EventRunView(id,template,type,EventState.SCHEDULED,world,x,y,z,now,null,null);
    }); }

    public CompletableFuture<Boolean> transition(UUID id, EventState expected, EventState next, Instant started, Instant ends, String detail) { return supply(() -> {
        try (Connection c = connection(); PreparedStatement p = c.prepareStatement("UPDATE event_runs SET state=?,started_at=COALESCE(?,started_at),ends_at=COALESCE(?,ends_at),detail=? WHERE run_id=? AND state=?")) {
            p.setString(1,next.name()); p.setObject(2,started); p.setObject(3,ends); p.setString(4,detail); p.setObject(5,id); p.setString(6,expected.name());
            boolean changed=p.executeUpdate()==1; if(changed) audit(id,"STATE_"+next.name(),detail); return changed;
        }
    }); }

    public CompletableFuture<List<EventRunView>> activeRuns() { return supply(() -> {
        List<EventRunView> result=new ArrayList<>();
        try(Connection c=connection(); PreparedStatement p=c.prepareStatement("SELECT * FROM event_runs WHERE state IN ('SCHEDULED','PREPARING','ACTIVE') ORDER BY created_at"); ResultSet r=p.executeQuery()){while(r.next())result.add(map(r));}
        return List.copyOf(result);
    }); }

    public CompletableFuture<Optional<EventRunView>> active(String template) { return supply(() -> {
        try(Connection c=connection(); PreparedStatement p=c.prepareStatement("SELECT * FROM event_runs WHERE template_id=? AND state IN ('SCHEDULED','PREPARING','ACTIVE') ORDER BY created_at DESC FETCH FIRST 1 ROW ONLY")){p.setString(1,template);try(ResultSet r=p.executeQuery()){return r.next()?Optional.of(map(r)):Optional.empty();}}
    }); }

    public CompletableFuture<Void> addDamage(UUID run, UUID player, String name, double damage) { return run(() -> {
        try(Connection c=connection(); PreparedStatement p=c.prepareStatement("MERGE INTO event_contributions(run_id,player_id,player_name,damage) KEY(run_id,player_id) VALUES(?,?,?,COALESCE((SELECT damage FROM event_contributions WHERE run_id=? AND player_id=?),0)+?)")){p.setObject(1,run);p.setObject(2,player);p.setString(3,name);p.setObject(4,run);p.setObject(5,player);p.setDouble(6,Math.max(0,damage));p.executeUpdate();}
    }); }

    public CompletableFuture<List<Contribution>> contributions(UUID run) { return supply(() -> {
        List<Contribution> out=new ArrayList<>();try(Connection c=connection();PreparedStatement p=c.prepareStatement("SELECT player_id,player_name,damage FROM event_contributions WHERE run_id=? ORDER BY damage DESC")){p.setObject(1,run);try(ResultSet r=p.executeQuery()){while(r.next())out.add(new Contribution(r.getObject(1,UUID.class),r.getString(2),r.getDouble(3)));}}return List.copyOf(out);
    }); }

    public CompletableFuture<RewardTransaction> journalReward(UUID run, UUID player, String name, String reward) { return supply(() -> {
        UUID tx=UUID.randomUUID();Instant now=Instant.now();try(Connection c=connection();PreparedStatement p=c.prepareStatement("INSERT INTO event_rewards VALUES(?,?,?,?,?,FALSE,?)")){p.setObject(1,tx);p.setObject(2,run);p.setObject(3,player);p.setString(4,name);p.setString(5,reward);p.setObject(6,now);p.executeUpdate();}return new RewardTransaction(tx,run,player,name,reward,false,now);
    }); }

    public CompletableFuture<List<RewardTransaction>> pendingRewards() { return supply(() -> {
        List<RewardTransaction> out=new ArrayList<>();try(Connection c=connection();PreparedStatement p=c.prepareStatement("SELECT * FROM event_rewards WHERE delivered=FALSE ORDER BY created_at");ResultSet r=p.executeQuery()){while(r.next())out.add(new RewardTransaction(r.getObject("transaction_id",UUID.class),r.getObject("run_id",UUID.class),r.getObject("player_id",UUID.class),r.getString("player_name"),r.getString("reward_id"),false,r.getObject("created_at",java.time.OffsetDateTime.class).toInstant()));}return List.copyOf(out);
    }); }

    public CompletableFuture<Boolean> markDelivered(UUID tx) { return supply(() -> {try(Connection c=connection();PreparedStatement p=c.prepareStatement("UPDATE event_rewards SET delivered=TRUE WHERE transaction_id=? AND delivered=FALSE")){p.setObject(1,tx);return p.executeUpdate()==1;}}); }
    public CompletableFuture<Integer> cancelOrphans() { return supply(() -> {try(Connection c=connection();Statement s=c.createStatement()){return s.executeUpdate("UPDATE event_runs SET state='CANCELLED',detail='startup reconciliation' WHERE state IN ('SCHEDULED','PREPARING','ACTIVE')");}}); }

    private Connection connection() throws SQLException { return DriverManager.getConnection(url,"sa",""); }
    private void audit(UUID id,String action,String detail)throws SQLException{try(Connection c=connection();PreparedStatement p=c.prepareStatement("INSERT INTO event_audit(run_id,action,detail,created_at) VALUES(?,?,?,?)")){p.setObject(1,id);p.setString(2,action);p.setString(3,detail);p.setObject(4,Instant.now());p.executeUpdate();}}
    private static EventRunView map(ResultSet r)throws SQLException{return new EventRunView(r.getObject("run_id",UUID.class),r.getString("template_id"),EventType.valueOf(r.getString("event_type")),EventState.valueOf(r.getString("state")),r.getString("world"),r.getInt("x"),r.getInt("y"),r.getInt("z"),instant(r,"created_at"),instant(r,"started_at"),instant(r,"ends_at"));}
    private static Instant instant(ResultSet r,String column)throws SQLException{var v=r.getObject(column,java.time.OffsetDateTime.class);return v==null?null:v.toInstant();}
    private <T> CompletableFuture<T> supply(SqlSupplier<T> task){return CompletableFuture.supplyAsync(()->{try{return task.get();}catch(SQLException e){throw new CompletionException(e);}},executor);}
    private CompletableFuture<Void> run(SqlRunnable task){return supply(()->{task.run();return null;});}
    @Override public void close(){executor.shutdown();}
    @FunctionalInterface private interface SqlSupplier<T>{T get()throws SQLException;}
    @FunctionalInterface private interface SqlRunnable{void run()throws SQLException;}
    public record Contribution(UUID playerId,String playerName,double damage){}
    public record RewardTransaction(UUID transactionId,UUID runId,UUID playerId,String playerName,String rewardId,boolean delivered,Instant createdAt){}
}
